# Sensor
GAME_WINDOW_TITLE = "Cook Serve Delicious"
GAME_WINDOW_WITHOUT_MARGIN = (0, 32, 769, 519)
SCREEN_OFFSET: (int, int) = (-1980 + 50, 957)


SCREENSHOT_LOGGER_LOGS_PATH = "logs"
SCREENSHOT_LOGGER_ENABLED = True
SCREENSHOT_LOGGER_IMAGE_NAME: None | str = None
SCREENSHOT_LOGGER_ROLLING_IMAGE_AMOUNT = 50
SCREENSHOT_LOGGER_EDIT_ENABLED = True

# Loop
MOVEMENT_ENABLED = True
